apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# apply secrets 
- secrets/git-ssh-secret.yaml 
- secrets/secret-git.yaml 
- secrets/secret-quay.yaml
- secrets/pipeline-service-account.yaml
- secrets/github-token.yaml
- secrets/server-secret.yaml
- secrets/secret-openai.yaml

# apply task 
- tasks/embedding.yaml 
- tasks/git-clone.yaml
- tasks/sendmail.yaml
- tasks/create-github-release.yaml
- tasks/generate-build-id.yaml

# pipeline 
- pipeline/data-pipeline.yaml
