apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# apply secrets 
- secrets/git-ssh-secret.yaml 
- secrets/secret-git.yaml 
- secrets/secret-quay.yaml
- secrets/default_service_account.yaml
- secrets/github-token.yaml
- secrets/server-secret.yaml

#roles 
# - roles/clusterrole.yaml
# - roles/clusterrolebinding.yaml
# - roles/account-ClusterRoleBinding.yaml

# apply task 
- tasks/embedding.yaml 
- tasks/git-clone.yaml
- tasks/sendmail.yaml
- tasks/create-github-release.yaml
- tasks/generate-build-id.yaml

# pipeline 
- pipeline/data-pipeline.yaml
#triggers 
