apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rag-data-pipeline
spec:
      params:
      - name: repo
        type: string
        default: git@github.com:ilan-pinto/lightspeed-rag-documents.git
        description: Plain text source repo git 
      - name: branch-name
        type: string
        description: The git branch to clone.
        default: main
      - name: plain-text-folder
        type: string
        description: Plain text folder path
        default: /workspace/source/ocp-product-docs-plaintext
      - name: question-folder
        type: string
        description: Plain text question-folder path
        default: /workspace/source/ocp-product-docs-plaintext/applications/deployments

      - name: tag
        type: string
        description: rag results base tag
        default: "0.0.4"

      workspaces:     
        - name: shared-workspace  

      tasks:
      - name: git-clone
        taskRef:
          name: git-clone
        workspaces:
            - name: source
              workspace: shared-workspace 
        params:
          - name: url
            value:  "$(params.repo)"    #git@gitlab.cee.redhat.com:ilpinto/rover-bot.git
          - name: revision 
            value: "$(params.branch-name)"  
          - name: subdirectory
            value: ""
          - name: deleteExisting
            value: "true"

      - name: local
        taskRef:
          name: embedding
        runAfter:
          - git-clone
        workspaces:
          - name: source
            workspace: shared-workspace  
          - name: output
            workspace: shared-workspace 
        params:
            - name: vector-db
              value: "local"

            - name: model-name
              value: local:BAAI/bge-base-en

            - name: plain-text-folder
              value: "$(params.plain-text-folder)"

            - name: collection-name
              value: ocp-local

            - name: output-folder
              value: local

            - name: question-folder
              value: "$(params.question-folder)"

      - name: create-docker-file
        taskRef:
          name: create-docker-file
        runAfter:
          - local
        workspaces:
          - name: output
            workspace: shared-workspace 


      - name: push-to-quay
        taskRef:
          name: buildah
        runAfter:
          - create-docker-file
        workspaces:
          - name: output
            workspace: shared-workspace  
        params:
            - name: IMAGE
              value: quay.io/redhat_emp1/lightspeed-rag
            - name: DOCKERFILE
              value: dockerfile.output

      # - name: chroma-local
      #   taskRef:
      #     name: embedding
      #   runAfter:
      #     - git-clone
      #   workspaces:
      #     - name: source
      #       workspace: shared-workspace  
      #     - name: output
      #       workspace: shared-workspace 
      #   params:
      #       - name: vector-db
      #         value: "chromadb-local"

      #       - name: model-name
      #         value: local:BAAI/bge-base-en

      #       - name: plain-text-folder
      #         value: "$(params.plain-text-folder)"

      #       - name: collection-name
      #         value: ocp-chromadb-local

      #       - name: output-folder
      #         value: chorma-local

      #       - name: question-folder
      #         value: "$(params.question-folder)"

      # - name: chroma-remote
      #   taskRef:
      #     name: embedding
      #   runAfter:
      #     - git-clone
      #   workspaces:
      #     - name: source
      #       workspace: shared-workspace  
      #     - name: output
      #       workspace: shared-workspace 
      #   params:
      #       - name: vector-db
      #         value: "chromadb"

      #       - name: vector-host
      #         value: "chroma-lightspeed.apps.cn-ai-lab.6aw6.p1.openshiftapps.com"
              
      #       - name: vector-port
      #         value: "80"
    
      #       - name: vector-header
      #         value: '{"Authorization":"GSe8ipXPZNp4gcVfHixWahi1najVNT6T"}'

      #       - name: model-name
      #         value: local

      #       - name: plain-text-folder
      #         value: "$(params.plain-text-folder)"

      #       - name: collection-name
      #         value: ocp-chromadb

      #       - name: output-folder
      #         value: chorma-remote 

      #       - name: question-folder
      #         value: "$(params.question-folder)"

      - name: create-github-release
        taskRef:
          name: create-github-release
        runAfter:
            - local 
        workspaces:
          - name: source
            workspace: shared-workspace  
          - name: release-notes
            workspace: shared-workspace 
          - name: output
            workspace: shared-workspace 
        params:
            - name: TAG
              value: $(params.tag)
            - name: REVISION
              value: "main"
          

      # - name: mail
      #   taskRef: 
      #     name: sendmail
      #   runAfter:
      #       - create-github-release
      #   params:
      #     - name:  server
      #       value: smtp-server-secret
      #     - name: subject
      #       value: "completed emmbadings"
      #     - name: body
      #       value: "you can check rover bot dev"
      #     - name: sender
      #       value: "<ilpinto@redhat.com>"
      #     - name: recipients
      #       value: "<ilpinto@redhat>"


