apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: question-gen-pipeline
spec: 
      params:
      - name: repo
        type: string
        default: git@github.com:ilan-pinto/lightspeed-rag-documents.git
        description: Plain text source repo git 
      - name: branch-name
        type: string
        description: The git branch to clone.
        default: main
      - name: plain-text-folder
        type: string
        description: Plain text folder path
        default: /workspace/source/ocp-product-docs-plaintext
      - name: question-main-folder
        type: string
        description: Plain text question-folder path
        default: /workspace/source/ocp-product-docs-plaintext
      - name: tag
        type: string
        description: rag results base tag
        default: "0.0.12"

      - name: chunk-size
        type: string
        description: chunk size for embedding
        default: "1024"

      - name: chunk-overlap
        type: string
        default: "20"
        description: chunk overlap for embedding

      - name: similarity
        type: string
        default: "1"

      - name: number-of-questions
        type: string
        default: "10"
        description: number of questions genarated for evaluation 


      workspaces:     
        - name: shared-workspace  

      tasks:
      - name: git-clone
        taskRef:
          name: git-clone
        workspaces:
            - name: source
              workspace: shared-workspace 
        params:
          - name: url
            value:  "$(params.repo)"    #git@gitlab.cee.redhat.com:ilpinto/rover-bot.git
          - name: revision 
            value: "$(params.branch-name)"  
          - name: subdirectory
            value: ""
          - name: deleteExisting
            value: "true"
      
      - name: question-gen
        taskRef:
          name: question-gen
        runAfter:
          - git-clone
        workspaces:
          - name: persist-source
            workspace: shared-workspace  
          - name: output
            workspace: shared-workspace 
          - name: source
            workspace: shared-workspace  
        params:
            - name: provider
              value: "bam"

            - name: model
              value: ibm/granite-13b-chat-v2

            - name: input-persist-dir
              value: "$(workspaces.output.path)/data/local"

            - name: question-main-folder
              value: "$(params.question-main-folder)" 

            - name: chunk-size
              value: "$(params.chunk-size)" 

            - name: chunk-overlap
              value: "$(params.chunk-overlap)" 

            - name: similarity
              value: "$(params.similarity)"  

            - name: number-of-questions
              value: "$(params.number-of-questions)"  

