kind: Secret
apiVersion: v1
metadata:
  name: github-token
data:
  GITHUB_TOKEN: >-
    Z2l0aHViX3BhdF8xMUFOV0lLTkkwM3VWa2U4aEp6ZTlEX2ZBMloyOXlCTWhWTVlIV3F2ZmJ5cHN6aVc2aFBQR2xqTWd6ZE5QYXZKbnBHTlJLUEZCTUx6ejgzSGtB
type: Opaque